//! Pins the Markdown rendering of real BlockNote documents.
//!
//! The `.json` files are generated by a real editor from
//! `apps/client/src/test/blocknoteFixtureCases.ts` (`npm run
//! fixtures:blocknote`); a drift test there fails if the editor changes its
//! shape. The `.md` files are the reviewed expected output of this crate.
//! Between them, neither side can move without a red test.
//!
//! Set `UPDATE_RICH_TEXT_FIXTURES=1` to rewrite the `.md` files, then read
//! the diff before committing it.

use std::fs;
use std::path::{Path, PathBuf};

use database_domain::rich_text::{from_markdown, to_markdown};

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/blocknote")
}

fn cases() -> Vec<PathBuf> {
    let mut cases: Vec<PathBuf> = fs::read_dir(fixture_dir())
        .expect("fixture directory is missing")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "json")
        })
        .collect();
    cases.sort();
    cases
}

#[test]
fn every_fixture_renders_to_its_expected_markdown() {
    let cases = cases();

    // Guard against an accidentally emptied directory turning this test
    // into a no-op that passes.
    assert!(
        cases.len() >= 5,
        "expected at least 5 fixtures, found {}",
        cases.len()
    );
    let names: Vec<String> = cases
        .iter()
        .filter_map(|path| path.file_stem())
        .map(|stem| stem.to_string_lossy().into_owned())
        .collect();
    for required in ["01-paragraph-blank-paragraph", "04-inline-styles"] {
        assert!(
            names.iter().any(|name| name == required),
            "fixture {required} is missing"
        );
    }

    let update = std::env::var("UPDATE_RICH_TEXT_FIXTURES").is_ok();

    for case in cases {
        let document: serde_json::Value = serde_json::from_str(
            &fs::read_to_string(&case).expect("readable fixture"),
        )
        .expect("fixture is valid JSON");

        let rendered = to_markdown(&document);
        let expected_path = case.with_extension("md");

        if update {
            fs::write(&expected_path, format!("{rendered}\n"))
                .expect("writable fixture");
            continue;
        }

        let expected =
            fs::read_to_string(&expected_path).unwrap_or_else(|_| {
                panic!(
                    "{} is missing; run with \
                     UPDATE_RICH_TEXT_FIXTURES=1",
                    expected_path.display()
                )
            });
        assert_eq!(
            rendered,
            expected.trim_end_matches('\n'),
            "{} rendered unexpectedly",
            case.display()
        );
    }
}

#[test]
fn markdown_round_trip_is_idempotent() {
    // Equality with the input is not achievable -- list markers, escaping
    // and fence style all normalize. Idempotence is the invariant that
    // actually matters: importing from GitHub twice must not keep changing
    // the document.
    for case in cases() {
        let expected_path = case.with_extension("md");
        let Ok(markdown) = fs::read_to_string(&expected_path) else {
            continue;
        };

        let once = to_markdown(&from_markdown(&markdown));
        let twice = to_markdown(&from_markdown(&once));
        assert_eq!(
            once,
            twice,
            "{} is not idempotent through markdown",
            case.display()
        );
    }
}

#[test]
fn malformed_documents_degrade_instead_of_panicking() {
    for document in [
        serde_json::json!(null),
        serde_json::json!("not a document"),
        serde_json::json!({}),
        serde_json::json!([{ "type": "paragraph" }]),
        serde_json::json!([{ "content": "no type" }]),
        serde_json::json!([{ "type": "somethingFromTheFuture",
                             "content": [
                                 { "type": "text", "text": "kept",
                                   "styles": {} }
                             ] }]),
    ] {
        let _ = to_markdown(&document);
    }

    // An unknown block keeps its text rather than dropping it.
    let future = serde_json::json!([{
        "type": "somethingFromTheFuture",
        "content": [{ "type": "text", "text": "kept", "styles": {} }],
    }]);
    assert_eq!(to_markdown(&future), "kept");
}

#[test]
fn empty_markdown_is_one_empty_paragraph_not_a_cleared_value() {
    let document = from_markdown("");
    assert_eq!(
        document,
        serde_json::json!([{
            "type": "paragraph",
            "props": {},
            "content": [],
            "children": [],
        }])
    );
}
