//! Action Registry
//!
//! This file is auto-generated from action! macro usages.
//! DO NOT EDIT MANUALLY.
//!
//! Generated by action-extractor tool.

use std::collections::HashMap;
use value_object::ActionString;

/// Actions for order context
pub mod order {
    use super::*;

    /// Action: order:CreateProduct
    pub const CREATEPRODUCT: &str = "order:CreateProduct";
    /// Action: order:GetProduct
    pub const GETPRODUCT: &str = "order:GetProduct";
    /// Action: order:GetProduct_v2
    pub const GETPRODUCT_V2: &str = "order:GetProduct_v2";
    /// Action: order:ListAllProducts
    pub const LISTALLPRODUCTS: &str = "order:ListAllProducts";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "order:CreateProduct",
            "order:GetProduct",
            "order:GetProduct_v2",
            "order:ListAllProducts",
        ]
    }
}

/// Actions for auth context
pub mod auth {
    use super::*;

    /// Action: auth:AttachServiceAccountPolicy
    pub const ATTACHSERVICEACCOUNTPOLICY: &str = "auth:AttachServiceAccountPolicy";
    /// Action: auth:AttachUserPolicy
    pub const ATTACHUSERPOLICY: &str = "auth:AttachUserPolicy";
    /// Action: auth:CreateOperator
    pub const CREATEOPERATOR: &str = "auth:CreateOperator";
    /// Action: auth:CreatePublicApiKey
    pub const CREATEPUBLICAPIKEY: &str = "auth:CreatePublicApiKey";
    /// Action: auth:CreateServiceAccount
    pub const CREATESERVICEACCOUNT: &str = "auth:CreateServiceAccount";
    /// Action: auth:CreateUser
    pub const CREATEUSER: &str = "auth:CreateUser";
    /// Action: auth:CreateUser123
    pub const CREATEUSER123: &str = "auth:CreateUser123";
    /// Action: auth:Create_User
    pub const CREATE_USER: &str = "auth:Create_User";
    /// Action: auth:DeleteOperator
    pub const DELETEOPERATOR: &str = "auth:DeleteOperator";
    /// Action: auth:DeleteServiceAccount
    pub const DELETESERVICEACCOUNT: &str = "auth:DeleteServiceAccount";
    /// Action: auth:DeleteUser
    pub const DELETEUSER: &str = "auth:DeleteUser";
    /// Action: auth:DetachServiceAccountPolicy
    pub const DETACHSERVICEACCOUNTPOLICY: &str = "auth:DetachServiceAccountPolicy";
    /// Action: auth:DetachUserPolicy
    pub const DETACHUSERPOLICY: &str = "auth:DetachUserPolicy";
    /// Action: auth:ExchangeOAuthToken
    pub const EXCHANGEOAUTHTOKEN: &str = "auth:ExchangeOAuthToken";
    /// Action: auth:FindAllOAuthTokens
    pub const FINDALLOAUTHTOKENS: &str = "auth:FindAllOAuthTokens";
    /// Action: auth:FindAllOperators
    pub const FINDALLOPERATORS: &str = "auth:FindAllOperators";
    /// Action: auth:FindAllOperatorsByUserId
    pub const FINDALLOPERATORSBYUSERID: &str = "auth:FindAllOperatorsByUserId";
    /// Action: auth:FindAllPlatform
    pub const FINDALLPLATFORM: &str = "auth:FindAllPlatform";
    /// Action: auth:FindAllPublicApiKeys
    pub const FINDALLPUBLICAPIKEYS: &str = "auth:FindAllPublicApiKeys";
    /// Action: auth:FindAllServiceAccounts
    pub const FINDALLSERVICEACCOUNTS: &str = "auth:FindAllServiceAccounts";
    /// Action: auth:FindAllUsers
    pub const FINDALLUSERS: &str = "auth:FindAllUsers";
    /// Action: auth:GetOAuthAuthorizationUrl
    pub const GETOAUTHAUTHORIZATIONURL: &str = "auth:GetOAuthAuthorizationUrl";
    /// Action: auth:GetOperatorByAlias
    pub const GETOPERATORBYALIAS: &str = "auth:GetOperatorByAlias";
    /// Action: auth:GetOperatorById
    pub const GETOPERATORBYID: &str = "auth:GetOperatorById";
    /// Action: auth:GetPlatform
    pub const GETPLATFORM: &str = "auth:GetPlatform";
    /// Action: auth:GetUser
    pub const GETUSER: &str = "auth:GetUser";
    /// Action: auth:GetUserById
    pub const GETUSERBYID: &str = "auth:GetUserById";
    /// Action: auth:InviteUser
    pub const INVITEUSER: &str = "auth:InviteUser";
    /// Action: auth:ListServiceAccountPolicies
    pub const LISTSERVICEACCOUNTPOLICIES: &str = "auth:ListServiceAccountPolicies";
    /// Action: auth:ListUserPolicies
    pub const LISTUSERPOLICIES: &str = "auth:ListUserPolicies";
    /// Action: auth:NewAction
    pub const NEWACTION: &str = "auth:NewAction";
    /// Action: auth:UpdatePolicy
    pub const UPDATEPOLICY: &str = "auth:UpdatePolicy";
    /// Action: auth:UpdateServiceAccount
    pub const UPDATESERVICEACCOUNT: &str = "auth:UpdateServiceAccount";
    /// Action: auth:a
    pub const A: &str = "auth:a";
    /// Action: auth:saveManifest
    pub const SAVEMANIFEST: &str = "auth:saveManifest";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "auth:",
            "auth:AttachServiceAccountPolicy",
            "auth:AttachUserPolicy",
            "auth:CreateOperator",
            "auth:CreatePublicApiKey",
            "auth:CreateServiceAccount",
            "auth:CreateUser",
            "auth:CreateUser123",
            "auth:Create_User",
            "auth:DeleteOperator",
            "auth:DeleteServiceAccount",
            "auth:DeleteUser",
            "auth:DetachServiceAccountPolicy",
            "auth:DetachUserPolicy",
            "auth:ExchangeOAuthToken",
            "auth:FindAllOAuthTokens",
            "auth:FindAllOperators",
            "auth:FindAllOperatorsByUserId",
            "auth:FindAllPlatform",
            "auth:FindAllPublicApiKeys",
            "auth:FindAllServiceAccounts",
            "auth:FindAllUsers",
            "auth:GetOAuthAuthorizationUrl",
            "auth:GetOperatorByAlias",
            "auth:GetOperatorById",
            "auth:GetPlatform",
            "auth:GetUser",
            "auth:GetUserById",
            "auth:InviteUser",
            "auth:ListServiceAccountPolicies",
            "auth:ListUserPolicies",
            "auth:NewAction",
            "auth:UpdatePolicy",
            "auth:UpdateServiceAccount",
            "auth:a",
            "auth:saveManifest",
        ]
    }
}

/// Actions for write context
pub mod write {
    use super::*;

    /// Action: write:deal_automation
    pub const DEAL_AUTOMATION: &str = "write:deal_automation";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "write:deal_automation",
        ]
    }
}

/// Actions for any context
pub mod any {
    use super::*;

    /// Action: any:action
    pub const ACTION: &str = "any:action";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "any:action",
        ]
    }
}

/// Actions for unknown context
pub mod unknown {
    use super::*;

    /// Action: unknown:action
    pub const ACTION: &str = "unknown:action";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "unknown:action",
        ]
    }
}

/// Actions for payment context
pub mod payment {
    use super::*;

    /// Action: payment:CreateBillingInfo
    pub const CREATEBILLINGINFO: &str = "payment:CreateBillingInfo";
    /// Action: payment:CreateBillingInformation
    pub const CREATEBILLINGINFORMATION: &str = "payment:CreateBillingInformation";
    /// Action: payment:CreateSetupIntent
    pub const CREATESETUPINTENT: &str = "payment:CreateSetupIntent";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "payment:CreateBillingInfo",
            "payment:CreateBillingInformation",
            "payment:CreateSetupIntent",
        ]
    }
}

/// Actions for test context
pub mod test {
    use super::*;

    /// Action: test:NonExistentAction
    pub const NONEXISTENTACTION: &str = "test:NonExistentAction";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "test:NonExistentAction",
        ]
    }
}

/// Actions for llms context
pub mod llms {
    use super::*;

    /// Action: llms:ExecuteAgent
    pub const EXECUTEAGENT: &str = "llms:ExecuteAgent";
    /// Action: llms:Execute_Agent_GPT4
    pub const EXECUTE_AGENT_GPT4: &str = "llms:Execute_Agent_GPT4";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            "llms:ExecuteAgent",
            "llms:Execute_Agent_GPT4",
        ]
    }
}

/// Actions for  context
pub mod  {
    use super::*;

    /// Action: :invalid
    pub const INVALID: &str = ":invalid";

    /// All actions in this context
    pub fn all_actions() -> Vec<&'static str> {
        vec![
            ":invalid",
        ]
    }
}

/// Global action registry
pub struct ActionRegistry {
    actions: HashMap<String, Vec<String>>,
}

impl ActionRegistry {
    /// Create a new action registry with all discovered actions
    pub fn new() -> Self {
        let mut actions = HashMap::new();

        actions.insert("order".to_string(), vec![
            "order:CreateProduct".to_string(),
            "order:GetProduct".to_string(),
            "order:GetProduct_v2".to_string(),
            "order:ListAllProducts".to_string(),
        ]);

        actions.insert("auth".to_string(), vec![
            "auth:".to_string(),
            "auth:AttachServiceAccountPolicy".to_string(),
            "auth:AttachUserPolicy".to_string(),
            "auth:CreateOperator".to_string(),
            "auth:CreatePublicApiKey".to_string(),
            "auth:CreateServiceAccount".to_string(),
            "auth:CreateUser".to_string(),
            "auth:CreateUser123".to_string(),
            "auth:Create_User".to_string(),
            "auth:DeleteOperator".to_string(),
            "auth:DeleteServiceAccount".to_string(),
            "auth:DeleteUser".to_string(),
            "auth:DetachServiceAccountPolicy".to_string(),
            "auth:DetachUserPolicy".to_string(),
            "auth:ExchangeOAuthToken".to_string(),
            "auth:FindAllOAuthTokens".to_string(),
            "auth:FindAllOperators".to_string(),
            "auth:FindAllOperatorsByUserId".to_string(),
            "auth:FindAllPlatform".to_string(),
            "auth:FindAllPublicApiKeys".to_string(),
            "auth:FindAllServiceAccounts".to_string(),
            "auth:FindAllUsers".to_string(),
            "auth:GetOAuthAuthorizationUrl".to_string(),
            "auth:GetOperatorByAlias".to_string(),
            "auth:GetOperatorById".to_string(),
            "auth:GetPlatform".to_string(),
            "auth:GetUser".to_string(),
            "auth:GetUserById".to_string(),
            "auth:InviteUser".to_string(),
            "auth:ListServiceAccountPolicies".to_string(),
            "auth:ListUserPolicies".to_string(),
            "auth:NewAction".to_string(),
            "auth:UpdatePolicy".to_string(),
            "auth:UpdateServiceAccount".to_string(),
            "auth:a".to_string(),
            "auth:saveManifest".to_string(),
        ]);

        actions.insert("write".to_string(), vec![
            "write:deal_automation".to_string(),
        ]);

        actions.insert("any".to_string(), vec![
            "any:action".to_string(),
        ]);

        actions.insert("unknown".to_string(), vec![
            "unknown:action".to_string(),
        ]);

        actions.insert("payment".to_string(), vec![
            "payment:CreateBillingInfo".to_string(),
            "payment:CreateBillingInformation".to_string(),
            "payment:CreateSetupIntent".to_string(),
        ]);

        actions.insert("test".to_string(), vec![
            "test:NonExistentAction".to_string(),
        ]);

        actions.insert("llms".to_string(), vec![
            "llms:ExecuteAgent".to_string(),
            "llms:Execute_Agent_GPT4".to_string(),
        ]);

        actions.insert("".to_string(), vec![
            ":invalid".to_string(),
        ]);

        Self { actions }
    }

    /// Get all actions for a specific context
    pub fn get_context_actions(&self, context: &str) -> Option<&Vec<String>> {
        self.actions.get(context)
    }

    /// Get all contexts
    pub fn get_contexts(&self) -> Vec<&String> {
        self.actions.keys().collect()
    }

    /// Get all actions across all contexts
    pub fn get_all_actions(&self) -> Vec<&String> {
        self.actions.values().flat_map(|v| v.iter()).collect()
    }

    /// Check if an action exists
    pub fn action_exists(&self, action: &str) -> bool {
        self.actions.values().any(|actions| actions.iter().any(|a| a == action))
    }

    /// Get action count by context
    pub fn get_action_count_by_context(&self) -> HashMap<&String, usize> {
        self.actions.iter().map(|(k, v)| (k, v.len())).collect()
    }
}

impl Default for ActionRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_action_registry() {
        let registry = ActionRegistry::new();
        assert_eq!(registry.get_contexts().len(), 9);
        assert_eq!(registry.get_all_actions().len(), 50);
        assert!(registry.action_exists("order:CreateProduct"));
        assert!(registry.action_exists("auth:"));
        assert!(registry.action_exists("write:deal_automation"));
        assert!(registry.action_exists("any:action"));
        assert!(registry.action_exists("unknown:action"));
        assert!(registry.action_exists("payment:CreateBillingInfo"));
        assert!(registry.action_exists("test:NonExistentAction"));
        assert!(registry.action_exists("llms:ExecuteAgent"));
        assert!(registry.action_exists(":invalid"));
    }
}
