import {
	DateValueForEditorFragment,
	IdValueForEditorFragment,
	ImageValueForEditorFragment,
	IntegerValueForEditorFragment,
	LocationValueForEditorFragment,
	MultiSelectValueForEditorFragment,
	PropertyDataForEditorFragment,
	PropertyDataInputData,
	PropertyForEditorFragment,
	PropertyType,
	RelationValueForEditorFragment,
	SelectValueForEditorFragment,
	StringValueForEditorFragment,
} from '@/gen/graphql'

type MarkdownValueFragment = Extract<
	PropertyDataForEditorFragment['value'],
	{ __typename?: 'MarkdownValue' }
>

type HtmlValueFragment = Extract<
	PropertyDataForEditorFragment['value'],
	{ __typename?: 'HtmlValue' }
>

type RichTextValueFragment = Extract<
	PropertyDataForEditorFragment['value'],
	{ __typename?: 'RichTextValue' }
>

// propertiesをみて、propertyDataの型を変える
export const convertPropertyData = (
	properties: PropertyForEditorFragment[],
	propertyData: PropertyDataForEditorFragment[],
): PropertyDataInputData[] => {
	return propertyData
		.map((x): PropertyDataInputData | null => {
			const property = properties.find(p => p.id === x.propertyId)
			if (!property) {
				throw new Error('Invalid property')
			}
			switch (property.typ) {
				case PropertyType.String:
					return {
						propertyId: x.propertyId,
						value: {
							string: (x.value as StringValueForEditorFragment).string,
						},
					} satisfies PropertyDataInputData
				case PropertyType.Html: {
					const htmlValue = x.value as HtmlValueFragment | undefined
					return {
						propertyId: x.propertyId,
						value: {
							html: htmlValue?.html ?? '',
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.Markdown: {
					const markdownValue = x.value as MarkdownValueFragment | undefined
					return {
						propertyId: x.propertyId,
						value: {
							markdown: markdownValue?.markdown ?? '',
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.RichText: {
					// Pass the document through untouched. This client renders the
					// markdown view but must never write it back -- markdown cannot
					// hold an empty paragraph, so writing the rendering would
					// destroy exactly what the type preserves.
					const richTextValue = x.value as RichTextValueFragment | undefined
					const richText = richTextValue?.richText ?? ''
					// Skip when the fragment did not deliver a document, rather than
					// overwriting the record's body with an empty one.
					if (!richText) {
						return null
					}
					return {
						propertyId: x.propertyId,
						value: {
							richText,
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.Integer:
					return {
						propertyId: x.propertyId,
						value: {
							integer: (x.value as IntegerValueForEditorFragment).number,
						},
					} satisfies PropertyDataInputData
				case PropertyType.Id: {
					const value = x.value as
						| IdValueForEditorFragment
						| StringValueForEditorFragment
					const isAutoGenerated =
						property.meta?.__typename === 'IdType' &&
						property.meta.autoGenerate
					if (isAutoGenerated && value.__typename !== 'IdValue') {
						if (value.__typename === 'StringValue' && !value.string) {
							// Older rows are projected by the API, but omit a stale empty
							// client value defensively instead of attempting to overwrite it.
							return null
						}
						throw new Error('Auto-generated Id cannot be edited')
					}
					return {
						propertyId: x.propertyId,
						value: {
							string: 'id' in value ? value.id : value.string,
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.Relation:
					return {
						propertyId: x.propertyId,
						value: {
							relation: (x.value as RelationValueForEditorFragment).dataIds,
						},
					} satisfies PropertyDataInputData
				case PropertyType.Select: {
					const selectValue = x.value as
						| SelectValueForEditorFragment
						| undefined
					const optionId = selectValue?.optionId ?? ''
					// Skip empty select values to avoid Oneof input objects error
					if (!optionId) {
						return null
					}
					return {
						propertyId: x.propertyId,
						value: {
							select: optionId,
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.MultiSelect:
					return {
						propertyId: x.propertyId,
						value: {
							multiSelect: (x.value as MultiSelectValueForEditorFragment)
								.optionIds,
						},
					} satisfies PropertyDataInputData
				case PropertyType.Location: {
					const locationValue = x.value as
						| LocationValueForEditorFragment
						| undefined
					return {
						propertyId: x.propertyId,
						value: {
							location: {
								latitude: locationValue?.latitude ?? 0,
								longitude: locationValue?.longitude ?? 0,
							},
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.Date: {
					const dateValue = x.value as DateValueForEditorFragment | undefined
					const date = dateValue?.date ?? ''
					// Skip empty date values to avoid Oneof input objects error
					if (!date) {
						return null
					}
					return {
						propertyId: x.propertyId,
						value: {
							date,
						},
					} satisfies PropertyDataInputData
				}
				case PropertyType.Image: {
					const imageValue = x.value as ImageValueForEditorFragment | undefined
					const url = imageValue?.url ?? ''
					// Skip empty image values to avoid Oneof input objects error
					if (!url) {
						return null
					}
					return {
						propertyId: x.propertyId,
						value: {
							image: url,
						},
					} satisfies PropertyDataInputData
				}
				default:
					throw new Error('Invalid property type')
			}
		})
		.filter((x): x is PropertyDataInputData => {
			return x !== null
		})
}
