/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config wrangler.public-docs.jsonc --env-interface PublicDocsEnv workers/public-docs/env.d.ts --include-runtime false` (hash: 06f2e2652d7ae11cea4dea39c484215b)
declare namespace Cloudflare {
	interface Env {
	}
}
interface PublicDocsEnv extends Cloudflare.Env {}
