/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V1betaRouteImport } from './routes/v1beta'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSign_upRouteImport } from './routes/_auth/sign_up'
import { Route as AuthSign_outRouteImport } from './routes/_auth/sign_out'
import { Route as AuthSign_inRouteImport } from './routes/_auth/sign_in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as V1betaOrgIndexRouteImport } from './routes/v1beta/$org/index'
import { Route as V1betaOrganizationNewRouteImport } from './routes/v1beta/organization/new'
import { Route as V1betaOrgRepoRouteImport } from './routes/v1beta/$org/$repo'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth/auth/callback'
import { Route as V1betaOrgRepoIndexRouteImport } from './routes/v1beta/$org/$repo/index'
import { Route as V1betaOrgRepoSettingsRouteImport } from './routes/v1beta/$org/$repo/settings'
import { Route as V1betaOrgRepoPropertiesRouteImport } from './routes/v1beta/$org/$repo/properties'
import { Route as V1betaOrgRepoDataRouteImport } from './routes/v1beta/$org/$repo/data'
import { Route as V1betaOrgRepoApiRouteImport } from './routes/v1beta/$org/$repo/api'
import { Route as V1betaOrgRepoDataNewRouteImport } from './routes/v1beta/$org/$repo/data/new'
import { Route as V1betaOrgRepoDataDataIdRouteImport } from './routes/v1beta/$org/$repo/data/$dataId'

const V1betaRoute = V1betaRouteImport.update({
  id: '/v1beta',
  path: '/v1beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSign_upRoute = AuthSign_upRouteImport.update({
  id: '/sign_up',
  path: '/sign_up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSign_outRoute = AuthSign_outRouteImport.update({
  id: '/sign_out',
  path: '/sign_out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSign_inRoute = AuthSign_inRouteImport.update({
  id: '/sign_in',
  path: '/sign_in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const V1betaOrgIndexRoute = V1betaOrgIndexRouteImport.update({
  id: '/$org/',
  path: '/$org/',
  getParentRoute: () => V1betaRoute,
} as any)
const V1betaOrganizationNewRoute = V1betaOrganizationNewRouteImport.update({
  id: '/organization/new',
  path: '/organization/new',
  getParentRoute: () => V1betaRoute,
} as any)
const V1betaOrgRepoRoute = V1betaOrgRepoRouteImport.update({
  id: '/$org/$repo',
  path: '/$org/$repo',
  getParentRoute: () => V1betaRoute,
} as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AuthRoute,
} as any)
const V1betaOrgRepoIndexRoute = V1betaOrgRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V1betaOrgRepoRoute,
} as any)
const V1betaOrgRepoSettingsRoute = V1betaOrgRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => V1betaOrgRepoRoute,
} as any)
const V1betaOrgRepoPropertiesRoute = V1betaOrgRepoPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => V1betaOrgRepoRoute,
} as any)
const V1betaOrgRepoDataRoute = V1betaOrgRepoDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => V1betaOrgRepoRoute,
} as any)
const V1betaOrgRepoApiRoute = V1betaOrgRepoApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => V1betaOrgRepoRoute,
} as any)
const V1betaOrgRepoDataNewRoute = V1betaOrgRepoDataNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => V1betaOrgRepoDataRoute,
} as any)
const V1betaOrgRepoDataDataIdRoute = V1betaOrgRepoDataDataIdRouteImport.update({
  id: '/$dataId',
  path: '/$dataId',
  getParentRoute: () => V1betaOrgRepoDataRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v1beta': typeof V1betaRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign_in': typeof AuthSign_inRoute
  '/sign_out': typeof AuthSign_outRoute
  '/sign_up': typeof AuthSign_upRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/v1beta/$org/$repo': typeof V1betaOrgRepoRouteWithChildren
  '/v1beta/organization/new': typeof V1betaOrganizationNewRoute
  '/v1beta/$org/': typeof V1betaOrgIndexRoute
  '/v1beta/$org/$repo/api': typeof V1betaOrgRepoApiRoute
  '/v1beta/$org/$repo/data': typeof V1betaOrgRepoDataRouteWithChildren
  '/v1beta/$org/$repo/properties': typeof V1betaOrgRepoPropertiesRoute
  '/v1beta/$org/$repo/settings': typeof V1betaOrgRepoSettingsRoute
  '/v1beta/$org/$repo/': typeof V1betaOrgRepoIndexRoute
  '/v1beta/$org/$repo/data/$dataId': typeof V1betaOrgRepoDataDataIdRoute
  '/v1beta/$org/$repo/data/new': typeof V1betaOrgRepoDataNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v1beta': typeof V1betaRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign_in': typeof AuthSign_inRoute
  '/sign_out': typeof AuthSign_outRoute
  '/sign_up': typeof AuthSign_upRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/v1beta/organization/new': typeof V1betaOrganizationNewRoute
  '/v1beta/$org': typeof V1betaOrgIndexRoute
  '/v1beta/$org/$repo/api': typeof V1betaOrgRepoApiRoute
  '/v1beta/$org/$repo/data': typeof V1betaOrgRepoDataRouteWithChildren
  '/v1beta/$org/$repo/properties': typeof V1betaOrgRepoPropertiesRoute
  '/v1beta/$org/$repo/settings': typeof V1betaOrgRepoSettingsRoute
  '/v1beta/$org/$repo': typeof V1betaOrgRepoIndexRoute
  '/v1beta/$org/$repo/data/$dataId': typeof V1betaOrgRepoDataDataIdRoute
  '/v1beta/$org/$repo/data/new': typeof V1betaOrgRepoDataNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/v1beta': typeof V1betaRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign_in': typeof AuthSign_inRoute
  '/_auth/sign_out': typeof AuthSign_outRoute
  '/_auth/sign_up': typeof AuthSign_upRoute
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/v1beta/$org/$repo': typeof V1betaOrgRepoRouteWithChildren
  '/v1beta/organization/new': typeof V1betaOrganizationNewRoute
  '/v1beta/$org/': typeof V1betaOrgIndexRoute
  '/v1beta/$org/$repo/api': typeof V1betaOrgRepoApiRoute
  '/v1beta/$org/$repo/data': typeof V1betaOrgRepoDataRouteWithChildren
  '/v1beta/$org/$repo/properties': typeof V1betaOrgRepoPropertiesRoute
  '/v1beta/$org/$repo/settings': typeof V1betaOrgRepoSettingsRoute
  '/v1beta/$org/$repo/': typeof V1betaOrgRepoIndexRoute
  '/v1beta/$org/$repo/data/$dataId': typeof V1betaOrgRepoDataDataIdRoute
  '/v1beta/$org/$repo/data/new': typeof V1betaOrgRepoDataNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v1beta'
    | '/forgot-password'
    | '/reset-password'
    | '/sign_in'
    | '/sign_out'
    | '/sign_up'
    | '/auth/callback'
    | '/v1beta/$org/$repo'
    | '/v1beta/organization/new'
    | '/v1beta/$org/'
    | '/v1beta/$org/$repo/api'
    | '/v1beta/$org/$repo/data'
    | '/v1beta/$org/$repo/properties'
    | '/v1beta/$org/$repo/settings'
    | '/v1beta/$org/$repo/'
    | '/v1beta/$org/$repo/data/$dataId'
    | '/v1beta/$org/$repo/data/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/v1beta'
    | '/forgot-password'
    | '/reset-password'
    | '/sign_in'
    | '/sign_out'
    | '/sign_up'
    | '/auth/callback'
    | '/v1beta/organization/new'
    | '/v1beta/$org'
    | '/v1beta/$org/$repo/api'
    | '/v1beta/$org/$repo/data'
    | '/v1beta/$org/$repo/properties'
    | '/v1beta/$org/$repo/settings'
    | '/v1beta/$org/$repo'
    | '/v1beta/$org/$repo/data/$dataId'
    | '/v1beta/$org/$repo/data/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/v1beta'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign_in'
    | '/_auth/sign_out'
    | '/_auth/sign_up'
    | '/_auth/auth/callback'
    | '/v1beta/$org/$repo'
    | '/v1beta/organization/new'
    | '/v1beta/$org/'
    | '/v1beta/$org/$repo/api'
    | '/v1beta/$org/$repo/data'
    | '/v1beta/$org/$repo/properties'
    | '/v1beta/$org/$repo/settings'
    | '/v1beta/$org/$repo/'
    | '/v1beta/$org/$repo/data/$dataId'
    | '/v1beta/$org/$repo/data/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  V1betaRoute: typeof V1betaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v1beta': {
      id: '/v1beta'
      path: '/v1beta'
      fullPath: '/v1beta'
      preLoaderRoute: typeof V1betaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign_up': {
      id: '/_auth/sign_up'
      path: '/sign_up'
      fullPath: '/sign_up'
      preLoaderRoute: typeof AuthSign_upRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign_out': {
      id: '/_auth/sign_out'
      path: '/sign_out'
      fullPath: '/sign_out'
      preLoaderRoute: typeof AuthSign_outRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign_in': {
      id: '/_auth/sign_in'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof AuthSign_inRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/v1beta/$org/': {
      id: '/v1beta/$org/'
      path: '/$org'
      fullPath: '/v1beta/$org/'
      preLoaderRoute: typeof V1betaOrgIndexRouteImport
      parentRoute: typeof V1betaRoute
    }
    '/v1beta/organization/new': {
      id: '/v1beta/organization/new'
      path: '/organization/new'
      fullPath: '/v1beta/organization/new'
      preLoaderRoute: typeof V1betaOrganizationNewRouteImport
      parentRoute: typeof V1betaRoute
    }
    '/v1beta/$org/$repo': {
      id: '/v1beta/$org/$repo'
      path: '/$org/$repo'
      fullPath: '/v1beta/$org/$repo'
      preLoaderRoute: typeof V1betaOrgRepoRouteImport
      parentRoute: typeof V1betaRoute
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/v1beta/$org/$repo/': {
      id: '/v1beta/$org/$repo/'
      path: '/'
      fullPath: '/v1beta/$org/$repo/'
      preLoaderRoute: typeof V1betaOrgRepoIndexRouteImport
      parentRoute: typeof V1betaOrgRepoRoute
    }
    '/v1beta/$org/$repo/settings': {
      id: '/v1beta/$org/$repo/settings'
      path: '/settings'
      fullPath: '/v1beta/$org/$repo/settings'
      preLoaderRoute: typeof V1betaOrgRepoSettingsRouteImport
      parentRoute: typeof V1betaOrgRepoRoute
    }
    '/v1beta/$org/$repo/properties': {
      id: '/v1beta/$org/$repo/properties'
      path: '/properties'
      fullPath: '/v1beta/$org/$repo/properties'
      preLoaderRoute: typeof V1betaOrgRepoPropertiesRouteImport
      parentRoute: typeof V1betaOrgRepoRoute
    }
    '/v1beta/$org/$repo/data': {
      id: '/v1beta/$org/$repo/data'
      path: '/data'
      fullPath: '/v1beta/$org/$repo/data'
      preLoaderRoute: typeof V1betaOrgRepoDataRouteImport
      parentRoute: typeof V1betaOrgRepoRoute
    }
    '/v1beta/$org/$repo/api': {
      id: '/v1beta/$org/$repo/api'
      path: '/api'
      fullPath: '/v1beta/$org/$repo/api'
      preLoaderRoute: typeof V1betaOrgRepoApiRouteImport
      parentRoute: typeof V1betaOrgRepoRoute
    }
    '/v1beta/$org/$repo/data/new': {
      id: '/v1beta/$org/$repo/data/new'
      path: '/new'
      fullPath: '/v1beta/$org/$repo/data/new'
      preLoaderRoute: typeof V1betaOrgRepoDataNewRouteImport
      parentRoute: typeof V1betaOrgRepoDataRoute
    }
    '/v1beta/$org/$repo/data/$dataId': {
      id: '/v1beta/$org/$repo/data/$dataId'
      path: '/$dataId'
      fullPath: '/v1beta/$org/$repo/data/$dataId'
      preLoaderRoute: typeof V1betaOrgRepoDataDataIdRouteImport
      parentRoute: typeof V1betaOrgRepoDataRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSign_inRoute: typeof AuthSign_inRoute
  AuthSign_outRoute: typeof AuthSign_outRoute
  AuthSign_upRoute: typeof AuthSign_upRoute
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSign_inRoute: AuthSign_inRoute,
  AuthSign_outRoute: AuthSign_outRoute,
  AuthSign_upRoute: AuthSign_upRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface V1betaOrgRepoDataRouteChildren {
  V1betaOrgRepoDataDataIdRoute: typeof V1betaOrgRepoDataDataIdRoute
  V1betaOrgRepoDataNewRoute: typeof V1betaOrgRepoDataNewRoute
}

const V1betaOrgRepoDataRouteChildren: V1betaOrgRepoDataRouteChildren = {
  V1betaOrgRepoDataDataIdRoute: V1betaOrgRepoDataDataIdRoute,
  V1betaOrgRepoDataNewRoute: V1betaOrgRepoDataNewRoute,
}

const V1betaOrgRepoDataRouteWithChildren =
  V1betaOrgRepoDataRoute._addFileChildren(V1betaOrgRepoDataRouteChildren)

interface V1betaOrgRepoRouteChildren {
  V1betaOrgRepoApiRoute: typeof V1betaOrgRepoApiRoute
  V1betaOrgRepoDataRoute: typeof V1betaOrgRepoDataRouteWithChildren
  V1betaOrgRepoPropertiesRoute: typeof V1betaOrgRepoPropertiesRoute
  V1betaOrgRepoSettingsRoute: typeof V1betaOrgRepoSettingsRoute
  V1betaOrgRepoIndexRoute: typeof V1betaOrgRepoIndexRoute
}

const V1betaOrgRepoRouteChildren: V1betaOrgRepoRouteChildren = {
  V1betaOrgRepoApiRoute: V1betaOrgRepoApiRoute,
  V1betaOrgRepoDataRoute: V1betaOrgRepoDataRouteWithChildren,
  V1betaOrgRepoPropertiesRoute: V1betaOrgRepoPropertiesRoute,
  V1betaOrgRepoSettingsRoute: V1betaOrgRepoSettingsRoute,
  V1betaOrgRepoIndexRoute: V1betaOrgRepoIndexRoute,
}

const V1betaOrgRepoRouteWithChildren = V1betaOrgRepoRoute._addFileChildren(
  V1betaOrgRepoRouteChildren,
)

interface V1betaRouteChildren {
  V1betaOrgRepoRoute: typeof V1betaOrgRepoRouteWithChildren
  V1betaOrganizationNewRoute: typeof V1betaOrganizationNewRoute
  V1betaOrgIndexRoute: typeof V1betaOrgIndexRoute
}

const V1betaRouteChildren: V1betaRouteChildren = {
  V1betaOrgRepoRoute: V1betaOrgRepoRouteWithChildren,
  V1betaOrganizationNewRoute: V1betaOrganizationNewRoute,
  V1betaOrgIndexRoute: V1betaOrgIndexRoute,
}

const V1betaRouteWithChildren =
  V1betaRoute._addFileChildren(V1betaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  V1betaRoute: V1betaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
