'use client'
import { Button } from '@/components/ui/button'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UL9NMI34B3D
 */
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/components/ui/use-toast'
import { createSdkPlatform } from '@/lib/api-action'
import { type ApiError } from '@/lib/apiClient'
import { zodResolver } from '@hookform/resolvers/zod'
import type { Session } from 'next-auth'
import { useRouter } from 'next/navigation'
import { useCallback } from 'react'
import {
	type SubmitErrorHandler,
	type SubmitHandler,
	useForm,
} from 'react-hook-form'
import { z } from 'zod'

const formStatesSchema = z.object({
	// 3-40 characters, alphanumeric, hyphen, or underscore
	userName: z
		.string()
		.min(3)
		.max(40)
		.regex(/^[a-zA-Z0-9_-]+$/),
	email: z.string().email(),
	password: z.string(),
})

type FormStates = z.infer<typeof formStatesSchema>

export function NewOrgForm({ session }: { session: Session }) {
	const router = useRouter()
	const { toast } = useToast()
	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm<FormStates>({
		resolver: zodResolver(formStatesSchema),
		reValidateMode: 'onChange',
	})

	console.log(errors)

	const handleOnValid: SubmitHandler<FormStates> = useCallback(
		async formStates => {
			try {
				// create account
				const sdk = await createSdkPlatform()
				// TODO: さきにuserを作成する
				// await sdk.createOperator({
				// 	input: {
				// 		newOperatorOwnerEmail: formStates.email,
				// 		newOperatorOwnerMethod: NewOperatorOwnerMethod.Create,
				// 		newOperatorOwnerPassword: formStates.password,
				// 		operatorAlias: formStates.userName,
				// 		operatorName: formStates.userName,
				// 		platformId: platformId,
				// 	},
				// })
				// backendでのサインアップは完了する
				// ここでサインインする
				toast({
					title: 'Account created',
					description: 'Please sign in to your account',
				})
				router.push('/new-org/success')
			} catch (error) {
				console.error(error)
				if (error instanceof z.ZodError) {
					console.log(error.issues)
					return
				}
				toast({
					variant: 'destructive',
					title: (error as ApiError).response.errors[0].extensions.code,
					description: (error as ApiError).response.errors[0].message,
				})
			}
		},
		[router, toast],
	)
	const handleOnInvalid: SubmitErrorHandler<FormStates> = useCallback(
		err => {
			console.log(err)
			toast({
				variant: 'destructive',
				title: 'Form validation error. Please check the form and try again.',
				description: err.root?.message,
			})
		},
		[toast],
	)

	return (
		<form
			onSubmit={handleSubmit(handleOnValid, handleOnInvalid)}
			id='new-org-form'
		>
			<Card className='w-full max-w-xl mx-auto my-8 p-6 bg-white shadow-md'>
				<CardHeader>
					<CardTitle>Create a new user and project</CardTitle>
					<CardDescription>
						A project contains all project files, including the revision
						history. Already have a project project
					</CardDescription>
				</CardHeader>
				<CardContent>
					<div className='grid w-full gap-4'>
						<div>
							<Label htmlFor='user-name'>User name*</Label>
							<Input
								{...register('userName')}
								placeholder='User name'
								className='mt-1'
							/>
							{errors.userName?.message ? (
								<p className='text-red-500'>{errors.userName.message}</p>
							) : (
								<p className='text-xs text-gray-500'>
									Username may only contain alphanumeric characters or single
									hyphens, and cannot begin or end with a hyphen.
								</p>
							)}
						</div>

						<div>
							<Label htmlFor='email'>Email*</Label>
							<Input
								{...register('email')}
								placeholder='Email'
								className='mt-1'
							/>
							{errors.email?.message && (
								<p className='text-red-500'>{errors.email.message}</p>
							)}
						</div>

						<div>
							<Label htmlFor='password'>Password*</Label>
							<Input
								{...register('password')}
								placeholder='Password'
								className='mt-1'
							/>
						</div>
					</div>
				</CardContent>
				<CardFooter className='flex justify-end'>
					<Button type='submit' formTarget='new-org-form'>
						Create project
					</Button>
				</CardFooter>
			</Card>
		</form>
	)
}
