/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.51.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateProductRequest : Request body for updating a product
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProductRequest {
    /// Billing cycle
    #[serde(
        rename = "billingCycle",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub billing_cycle: Option<Option<String>>,
    /// Product category master value
    #[serde(
        rename = "category",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub category: Option<Option<String>>,
    /// Product description
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Updated image file IDs
    #[serde(
        rename = "imageFileIds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub image_file_ids: Option<Option<Vec<String>>>,
    /// Expected product updatedAt value for optimistic concurrency
    #[serde(
        rename = "expectedUpdatedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_updated_at: Option<Option<String>>,
    /// JAN code
    #[serde(
        rename = "janCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub jan_code: Option<Option<String>>,
    /// Product type
    #[serde(
        rename = "kind",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub kind: Option<Option<String>>,
    /// List price
    #[serde(
        rename = "listPrice",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub list_price: Option<Option<i32>>,
    /// Product name
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// Publication description
    #[serde(
        rename = "publicationDescription",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub publication_description: Option<Option<String>>,
    /// Publication name
    #[serde(
        rename = "publicationName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub publication_name: Option<Option<String>>,
    /// Publication status
    #[serde(
        rename = "publicationStatus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub publication_status: Option<Option<String>>,
    /// SKU code
    #[serde(
        rename = "skuCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sku_code: Option<Option<String>>,
    /// Product status
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<String>>,
    /// Product subcategory master value
    #[serde(
        rename = "subcategory",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subcategory: Option<Option<String>>,
    /// UPC code
    #[serde(
        rename = "upcCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub upc_code: Option<Option<String>>,
    /// Updated variations
    #[serde(
        rename = "variations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variations:
        Option<Option<Vec<models::UpdateProductVariationRequest>>>,
}

impl UpdateProductRequest {
    /// Request body for updating a product
    pub fn new() -> UpdateProductRequest {
        UpdateProductRequest {
            billing_cycle: None,
            category: None,
            description: None,
            image_file_ids: None,
            expected_updated_at: None,
            jan_code: None,
            kind: None,
            list_price: None,
            name: None,
            publication_description: None,
            publication_name: None,
            publication_status: None,
            sku_code: None,
            status: None,
            subcategory: None,
            upc_code: None,
            variations: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::UpdateProductRequest;

    #[test]
    fn serializes_category_master_write_contract() {
        let mut request = UpdateProductRequest::new();
        request.category = Some(Some("electronics".to_string()));
        request.subcategory = Some(Some("audio".to_string()));
        request.expected_updated_at =
            Some(Some("2026-05-24T12:00:00Z".to_string()));

        let value =
            serde_json::to_value(request).expect("request serializes");

        assert_eq!(value["category"], "electronics");
        assert_eq!(value["subcategory"], "audio");
        assert_eq!(value["expectedUpdatedAt"], "2026-05-24T12:00:00Z");
    }

    #[test]
    fn serializes_null_category_to_clear_master_value() {
        let mut request = UpdateProductRequest::new();
        request.category = Some(None);
        request.subcategory = Some(None);

        let value =
            serde_json::to_value(request).expect("request serializes");

        assert!(value
            .get("category")
            .is_some_and(serde_json::Value::is_null));
        assert!(value
            .get("subcategory")
            .is_some_and(serde_json::Value::is_null));
    }
}
