[package]
name = "library-worker-common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
worker.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys.workspace = true
futures.workspace = true
percent-encoding.workspace = true
base64.workspace = true
sha2.workspace = true
