//! Hand-made fixtures shaped like the official workbooks.
//!
//! Generated by `apps/cli/tests/fixtures/food/make_fixtures.py`; see that
//! script for what each row exercises.

use super::sheet::{Sheet, Workbook};

pub const TABLE_XLSX: &[u8] =
    include_bytes!("../../../tests/fixtures/food/mext_table_fixture.xlsx");
pub const ERRATA_XLSX: &[u8] =
    include_bytes!("../../../tests/fixtures/food/mext_errata_fixture.xlsx");

pub fn table_book() -> Workbook {
    Workbook::read_xlsx(TABLE_XLSX).unwrap()
}

pub fn errata_book() -> Workbook {
    Workbook::read_xlsx(ERRATA_XLSX).unwrap()
}

pub fn main_sheet() -> Sheet {
    table_book().sheet("表全体").unwrap().clone()
}
