//! Convert BlockNote block documents to and from Markdown.
//!
//! A [BlockNote](https://www.blocknotejs.org/) document is a tree of
//! blocks, stored as JSON. That representation is lossless; Markdown is
//! not -- it cannot hold an empty paragraph, for one -- so the two
//! directions are asymmetric by design:
//!
//! - [`to_markdown`] is total: it never panics and never fails. Malformed
//!   or unrecognized blocks degrade to their text rather than erroring,
//!   because rendering runs on read paths where an error is an outage.
//! - [`from_markdown`] covers the common subset (paragraphs, headings,
//!   lists, code, quotes, images) and is lossy by nature.
//! - [`to_html`] walks the tree directly rather than round-tripping
//!   through Markdown, so it keeps what Markdown cannot hold: the empty
//!   paragraph (`<p><br></p>`) and underline.
//! - [`plain_text`] extracts the document's text with no Markdown syntax,
//!   for search indexing and previews.
//!
//! The golden tests under `tests/` pin this crate against documents
//! generated by a real BlockNote editor, so drift on either side of the
//! contract turns a test red.

use serde_json::Value;

mod from_markdown;
mod inline;
mod to_html;
mod to_markdown;

pub use from_markdown::from_markdown;
pub use inline::plain_text;
pub use to_html::to_html;
pub use to_markdown::to_markdown;

/// The block array of a document.
///
/// Accepts either a bare array or an object wrapping one under `blocks`, so
/// that a client which adds an envelope does not break every read path.
pub(crate) fn blocks_of(document: &Value) -> &[Value] {
    if let Some(blocks) = document.as_array() {
        return blocks;
    }
    document
        .get("blocks")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[])
}
