'use client'
import { Button } from '@/components/ui/button'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UL9NMI34B3D
 */
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from '@/components/ui/card'
import {
	Form,
	FormControl,
	FormDescription,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from '@/components/ui/form'
import { Label } from '@/components/ui/label'
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select'
import { useToast } from '@/components/ui/use-toast'
import {
	NewOperatorOwnerMethod,
	type OrganizationOptionFragment,
} from '@/gen/graphql'
import { type ApiError, getSdkPlatform, platformId } from '@/lib/apiClient'
import { zodResolver } from '@hookform/resolvers/zod'
import type { Session } from 'next-auth'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useCallback } from 'react'
import {
	type SubmitErrorHandler,
	type SubmitHandler,
	useForm,
} from 'react-hook-form'
import { z } from 'zod'

const formStatesSchema = z.object({
	// 3-40 characters, alphanumeric, hyphen, or underscore
	userName: z
		.string()
		.min(3)
		.max(40)
		.regex(/^[a-zA-Z0-9_-]+$/),
})

type FormStates = z.infer<typeof formStatesSchema>

export function NewRepoForm({
	userId,
	organizations,
	session: { user },
}: {
	userId: string
	organizations: OrganizationOptionFragment[]
	session: Session
}) {
	const router = useRouter()
	const { toast } = useToast()
	const form = useForm<FormStates>({
		resolver: zodResolver(formStatesSchema),
		reValidateMode: 'onChange',
	})

	const handleOnValid: SubmitHandler<FormStates> = useCallback(
		async formStates => {
			try {
				// オペレーターを作成
				const sdk = await getSdkPlatform(user.accessToken)
				await sdk.createOperator({
					input: {
						platformId,
						operatorName: formStates.userName,
						newOperatorOwnerId: userId,
						newOperatorOwnerMethod: NewOperatorOwnerMethod.Inherit,
					},
				})
				// backendでのサインアップは完了する
				// ここでサインインする
				router.push('/')
				console.log('valid')
			} catch (error) {
				console.error(error)
				if (error instanceof z.ZodError) {
					console.log(error.issues)
					return
				}
				toast({
					variant: 'destructive',
					title: (error as ApiError).response.errors[0].extensions.code,
					description: (error as ApiError).response.errors[0].message,
				})
			}
		},
		[router, toast, userId],
	)
	const handleOnInvalid: SubmitErrorHandler<FormStates> = useCallback(
		err => {
			console.log(err)
			toast({
				variant: 'destructive',
				title: 'Form validation error. Please check the form and try again.',
				description: err.root?.message,
			})
		},
		[toast],
	)

	return (
		<Form {...form}>
			<form
				onSubmit={form.handleSubmit(handleOnValid, handleOnInvalid)}
				id='new-org-form'
			>
				<Card className='w-full max-w-xl mx-auto my-8 p-6 bg-white shadow-md'>
					<CardHeader>
						<CardTitle>Create a new organization and project</CardTitle>
						<CardDescription>
							A project contains all project files, including the revision
							history. Already have a project project
						</CardDescription>
					</CardHeader>
					<CardContent>
						<div className='grid w-full gap-4'>
							<div className='flex'>
								<div>
									<Label htmlFor='user-name'>User name*</Label>
									<FormField
										control={form.control}
										name='userName'
										render={({ field }) => (
											<FormItem>
												<FormLabel>Email</FormLabel>
												<Select
													onValueChange={field.onChange}
													defaultValue={field.value}
												>
													<FormControl>
														<SelectTrigger>
															<SelectValue placeholder='Select a verified email to display' />
														</SelectTrigger>
													</FormControl>
													<SelectContent>
														<SelectItem value='m@example.com'>
															m@example.com
														</SelectItem>
														<SelectItem value='m@google.com'>
															m@google.com
														</SelectItem>
														<SelectItem value='m@support.com'>
															m@support.com
														</SelectItem>
													</SelectContent>
												</Select>
												<FormDescription>
													You can manage email addresses in your{' '}
													<Link href='/examples/forms'>email settings</Link>.
												</FormDescription>
												<FormMessage />
											</FormItem>
										)}
									/>
								</div>

								<FormField
									control={form.control}
									name='userName'
									render={({ field }) => (
										<FormItem>
											<FormLabel>username</FormLabel>
											<Select
												onValueChange={field.onChange}
												defaultValue={field.value}
											>
												<FormControl>
													<SelectTrigger>
														<SelectValue placeholder='Select a verified email to display' />
													</SelectTrigger>
												</FormControl>
												<SelectContent>
													<SelectItem value='m@example.com'>
														m@example.com
													</SelectItem>
													<SelectItem value='m@google.com'>
														m@google.com
													</SelectItem>
													<SelectItem value='m@support.com'>
														m@support.com
													</SelectItem>
												</SelectContent>
											</Select>
											<FormDescription>
												You can manage email addresses in your{' '}
												<Link href='/examples/forms'>email settings</Link>.
											</FormDescription>
											<FormMessage />
										</FormItem>
									)}
								/>
							</div>
						</div>
					</CardContent>
					<CardFooter className='flex justify-end'>
						<Button type='submit' formTarget='new-org-form'>
							Create organization
						</Button>
					</CardFooter>
				</Card>
			</form>
		</Form>
	)
}
