//! Pins the Markdown rendering of real BlockNote documents.
//!
//! The `.json` files are generated by a real editor from
//! `apps/client/src/test/blocknoteFixtureCases.ts` (`npm run
//! fixtures:blocknote` in apps/client); a drift test there fails if the
//! editor changes its shape. The `.md` files are the reviewed expected
//! output of this crate.
//! Between them, neither side can move without a red test.
//!
//! Set `UPDATE_RICH_TEXT_FIXTURES=1` to rewrite the `.md` files, then read
//! the diff before committing it.

use std::fs;
use std::path::{Path, PathBuf};

use blocknote::{from_markdown, to_html, to_markdown};

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn cases() -> Vec<PathBuf> {
    let mut cases: Vec<PathBuf> = fs::read_dir(fixture_dir())
        .expect("fixture directory is missing")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "json")
        })
        .collect();
    cases.sort();
    cases
}

#[test]
fn every_fixture_renders_to_its_expected_markdown() {
    let cases = cases();

    // Guard against an accidentally emptied directory turning this test
    // into a no-op that passes.
    assert!(
        cases.len() >= 5,
        "expected at least 5 fixtures, found {}",
        cases.len()
    );
    let names: Vec<String> = cases
        .iter()
        .filter_map(|path| path.file_stem())
        .map(|stem| stem.to_string_lossy().into_owned())
        .collect();
    for required in ["01-paragraph-blank-paragraph", "04-inline-styles"] {
        assert!(
            names.iter().any(|name| name == required),
            "fixture {required} is missing"
        );
    }

    let update = std::env::var("UPDATE_RICH_TEXT_FIXTURES").is_ok();

    for case in cases {
        let document: serde_json::Value = serde_json::from_str(
            &fs::read_to_string(&case).expect("readable fixture"),
        )
        .expect("fixture is valid JSON");

        for (rendered, extension) in
            [(to_markdown(&document), "md"), (to_html(&document), "html")]
        {
            let expected_path = case.with_extension(extension);

            if update {
                fs::write(&expected_path, format!("{rendered}\n"))
                    .expect("writable fixture");
                continue;
            }

            let expected = fs::read_to_string(&expected_path)
                .unwrap_or_else(|_| {
                    panic!(
                        "{} is missing; run with \
                         UPDATE_RICH_TEXT_FIXTURES=1",
                        expected_path.display()
                    )
                });
            assert_eq!(
                rendered,
                expected.trim_end_matches('\n'),
                "{} rendered unexpectedly",
                case.display()
            );
        }
    }
}

#[test]
fn html_keeps_the_empty_paragraph_that_markdown_cannot() {
    let document = serde_json::json!([
        { "type": "paragraph",
          "content": [{ "type": "text", "text": "line1", "styles": {} }] },
        { "type": "paragraph", "content": [] },
        { "type": "paragraph",
          "content": [{ "type": "text", "text": "line2", "styles": {} }] },
    ]);
    assert_eq!(to_html(&document), "<p>line1</p><p><br></p><p>line2</p>");
    // The same document through markdown loses the blank line -- that
    // contrast is why the html view exists.
    assert_eq!(to_markdown(&document), "line1\n\nline2");
}

#[test]
fn markdown_round_trip_is_idempotent() {
    // Equality with the input is not achievable -- list markers, escaping
    // and fence style all normalize. Idempotence is the invariant that
    // actually matters: importing from GitHub twice must not keep changing
    // the document.
    for case in cases() {
        let expected_path = case.with_extension("md");
        let Ok(markdown) = fs::read_to_string(&expected_path) else {
            continue;
        };

        let once = to_markdown(&from_markdown(&markdown));
        let twice = to_markdown(&from_markdown(&once));
        assert_eq!(
            once,
            twice,
            "{} is not idempotent through markdown",
            case.display()
        );
    }
}

#[test]
fn html_preview_round_trips_through_markdown() {
    let source = "<!doctype html>\n<button onclick=\"go()\">Go</button>";
    let document = serde_json::json!([{
        "type": "htmlPreview",
        "props": { "source": source },
        "children": [],
    }]);

    let markdown = to_markdown(&document);
    assert_eq!(markdown, format!("```html preview\n{source}\n```"));

    // The `preview` info word is what rebuilds the block; without the
    // round trip a GitHub-side edit would demote it to a code block and
    // the preview would be lost.
    let back = from_markdown(&markdown);
    assert_eq!(back[0]["type"], "htmlPreview");
    assert_eq!(back[0]["props"]["source"], source);

    // A plain ```html fence is somebody's code sample, not a preview.
    let code = from_markdown("```html\n<p>hi</p>\n```");
    assert_eq!(code[0]["type"], "codeBlock");
}

#[test]
fn html_preview_renders_as_a_sandboxed_iframe() {
    let document = serde_json::json!([{
        "type": "htmlPreview",
        "props": { "source": "<b>x & \"y\"</b>" },
        "children": [],
    }]);
    let html = blocknote::to_html(&document);
    assert!(html.starts_with("<iframe"), "got: {html}");
    assert!(html.contains("sandbox=\"allow-scripts\""));
    // Attribute-escaped, so the srcdoc cannot break out of the quotes.
    assert!(
        html.contains(
            "srcdoc=\"&lt;b&gt;x &amp; &quot;y&quot;&lt;/b&gt;\""
        ),
        "got: {html}"
    );
    // The source still counts as text: a body holding only a preview must
    // not be treated as an empty (cleared) value.
    assert!(!blocknote::plain_text(&document).is_empty());
}

#[test]
fn malformed_documents_degrade_instead_of_panicking() {
    for document in [
        serde_json::json!(null),
        serde_json::json!("not a document"),
        serde_json::json!({}),
        serde_json::json!([{ "type": "paragraph" }]),
        serde_json::json!([{ "content": "no type" }]),
        serde_json::json!([{ "type": "somethingFromTheFuture",
                             "content": [
                                 { "type": "text", "text": "kept",
                                   "styles": {} }
                             ] }]),
    ] {
        let _ = to_markdown(&document);
    }

    // An unknown block keeps its text rather than dropping it.
    let future = serde_json::json!([{
        "type": "somethingFromTheFuture",
        "content": [{ "type": "text", "text": "kept", "styles": {} }],
    }]);
    assert_eq!(to_markdown(&future), "kept");
}

#[test]
fn empty_markdown_is_one_empty_paragraph_not_a_cleared_value() {
    let document = from_markdown("");
    assert_eq!(
        document,
        serde_json::json!([{
            "type": "paragraph",
            "props": {},
            "content": [],
            "children": [],
        }])
    );
}
